<a href="https://colab.research.google.com/github/teemus28/Machine-Learning/blob/main/Library2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l1=[23,54,87,12]

In [ ]:
my_arr=np.array(l1)

In [ ]:
my_arr

array([23, 54, 87, 12])

In [ ]:
my_arr[1]

54

In [ ]:
my_arr.shape

(4,)

In [ ]:
my_arr.size

4

In [ ]:
my_arr.dtype

dtype('int64')

In [ ]:
l2=[[34,65,98],[67,34,65]]
my_arr_2d=np.array(l2)

In [ ]:
my_arr_2d.size

6

In [ ]:
my_arr_2d[0,1]

65

In [ ]:
my_arr_2d[1,2]=66   #changing value
my_arr_2d

array([[34, 65, 98],
       [67, 34, 66]])

In [ ]:
#ways to create np array

#a using list or tuple like above
#b using methods

In [ ]:
zeros = np.zeros(4)    #create an array having only zero
print(zeros)

[0. 0. 0. 0.]


In [ ]:
zeroes_2d = np.zeros((2,4))
zeroes_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
rng=np.arange(12)  #create an arraay having values b/w 0-11
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
lspace = np.linspace(1,20,6)   #creates an array having 6 equally spaced values b/w 1-20
lspace

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [ ]:
emp=np.empty((3,5))    #creates an empty array
emp

array([[5.04340234e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.16709769e-312],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05162486e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.32404027e-322]])

In [ ]:
# ar = np.array([1,2,3,4])
# # np.empty_like(ar)
# ar
# ar_2 = np.empty_like(ar)


In [ ]:
ide = np.identity(20)   #creates an identity matrix of 20X20
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [ ]:
ide.shape

(20, 20)

Reshaping array


In [ ]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.reshape(3,33)   #it becomes 3d
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()  #becomes 1 d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

Axis and methods in numpy


In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
array = np.array(l)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array.sum(axis=0)  #sum rows and creates 1d array

array([12, 15, 18])

In [ ]:
array.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
array.T   #transpose array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
array.flat  #breaks array into elements

In [ ]:
for i in array.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
array.ndim   #dimension

2

In [ ]:
array.size

9

In [ ]:
one = np.array([2,5,98,23])
one.argmax()     #returns index of max'm value in array


2

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()  #describe index in increasing order

array([0, 1, 3, 2])

In [ ]:
my_arr_2d

array([[34, 65, 98],
       [67, 34, 66]])

In [ ]:
my_arr_2d[1,1]=99
my_arr_2d


array([[34, 65, 98],
       [67, 99, 66]])

In [ ]:
my_arr_2d.argmin()  #creates 1d array and give value

0

In [ ]:
my_arr_2d.argmax()

4

In [ ]:
# my_arr_2d.argsort()

In [ ]:
my_arr_2d.argmin(axis=0)  #compare rows

array([0, 1, 1])

In [ ]:
my_arr_2d.argsort(axis=0)

array([[0, 0, 1],
       [1, 1, 0]])

In [ ]:
one

array([ 2,  5, 98, 23])

In [ ]:
my_arr_2d.sum()

364

In [ ]:
one.sum()

128

In [ ]:
one.max()

98

In [ ]:
one.min()

2

In [ ]:
np.where(one>24)

(array([2]),)

In [ ]:
np.where(my_arr_2d>70)

(array([0]), array([2]))

In [ ]:
np.count_nonzero(my_arr_2d)

6

In [ ]:
my_arr_2d.tolist()   #create list

[[34, 65, 98], [67, 34, 66]]